version: '3.8'

services:
  # PHP/Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orange-tree-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - orange-tree-network

  # Nginx Service
  nginx:
    image: nginx:1.25-alpine
    container_name: orange-tree-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - orange-tree-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: orange-tree-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: orange_tree
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: orange_tree_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - orange-tree-network

  # Node Service for Vue.js
  node:
    image: node:20-alpine
    container_name: orange-tree-node
    command: /bin/sh -c "while true; do sleep 1; done"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - orange-tree-network

networks:
  orange-tree-network:
    driver: bridge

volumes:
  dbdata: 